/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RedesignIndexRouteImport } from './routes/redesign/index'
import { Route as WorkflowNewRouteImport } from './routes/workflow/new'
import { Route as WorkflowNewIndexRouteImport } from './routes/workflow/new.index'
import { Route as WorkflowWorkflowIdEditRouteImport } from './routes/workflow/$workflowId/edit'
import { Route as WorkflowWorkflowIdEditIndexRouteImport } from './routes/workflow/$workflowId/edit.index'
import { Route as WorkflowNewStepStepRouteImport } from './routes/workflow/new.step.$step'
import { Route as WorkflowWorkflowIdEditStepStepRouteImport } from './routes/workflow/$workflowId/edit.step.$step'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesignIndexRoute = RedesignIndexRouteImport.update({
  id: '/redesign/',
  path: '/redesign/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowNewRoute = WorkflowNewRouteImport.update({
  id: '/workflow/new',
  path: '/workflow/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowNewIndexRoute = WorkflowNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowNewRoute,
} as any)
const WorkflowWorkflowIdEditRoute = WorkflowWorkflowIdEditRouteImport.update({
  id: '/workflow/$workflowId/edit',
  path: '/workflow/$workflowId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowWorkflowIdEditIndexRoute =
  WorkflowWorkflowIdEditIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkflowWorkflowIdEditRoute,
  } as any)
const WorkflowNewStepStepRoute = WorkflowNewStepStepRouteImport.update({
  id: '/step/$step',
  path: '/step/$step',
  getParentRoute: () => WorkflowNewRoute,
} as any)
const WorkflowWorkflowIdEditStepStepRoute =
  WorkflowWorkflowIdEditStepStepRouteImport.update({
    id: '/step/$step',
    path: '/step/$step',
    getParentRoute: () => WorkflowWorkflowIdEditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/workflow/new': typeof WorkflowNewRouteWithChildren
  '/redesign/': typeof RedesignIndexRoute
  '/workflow/$workflowId/edit': typeof WorkflowWorkflowIdEditRouteWithChildren
  '/workflow/new/': typeof WorkflowNewIndexRoute
  '/workflow/new/step/$step': typeof WorkflowNewStepStepRoute
  '/workflow/$workflowId/edit/': typeof WorkflowWorkflowIdEditIndexRoute
  '/workflow/$workflowId/edit/step/$step': typeof WorkflowWorkflowIdEditStepStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/redesign': typeof RedesignIndexRoute
  '/workflow/new': typeof WorkflowNewIndexRoute
  '/workflow/new/step/$step': typeof WorkflowNewStepStepRoute
  '/workflow/$workflowId/edit': typeof WorkflowWorkflowIdEditIndexRoute
  '/workflow/$workflowId/edit/step/$step': typeof WorkflowWorkflowIdEditStepStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/workflow/new': typeof WorkflowNewRouteWithChildren
  '/redesign/': typeof RedesignIndexRoute
  '/workflow/$workflowId/edit': typeof WorkflowWorkflowIdEditRouteWithChildren
  '/workflow/new/': typeof WorkflowNewIndexRoute
  '/workflow/new/step/$step': typeof WorkflowNewStepStepRoute
  '/workflow/$workflowId/edit/': typeof WorkflowWorkflowIdEditIndexRoute
  '/workflow/$workflowId/edit/step/$step': typeof WorkflowWorkflowIdEditStepStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/workflow/new'
    | '/redesign/'
    | '/workflow/$workflowId/edit'
    | '/workflow/new/'
    | '/workflow/new/step/$step'
    | '/workflow/$workflowId/edit/'
    | '/workflow/$workflowId/edit/step/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/redesign'
    | '/workflow/new'
    | '/workflow/new/step/$step'
    | '/workflow/$workflowId/edit'
    | '/workflow/$workflowId/edit/step/$step'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/workflow/new'
    | '/redesign/'
    | '/workflow/$workflowId/edit'
    | '/workflow/new/'
    | '/workflow/new/step/$step'
    | '/workflow/$workflowId/edit/'
    | '/workflow/$workflowId/edit/step/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  WorkflowNewRoute: typeof WorkflowNewRouteWithChildren
  RedesignIndexRoute: typeof RedesignIndexRoute
  WorkflowWorkflowIdEditRoute: typeof WorkflowWorkflowIdEditRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redesign/': {
      id: '/redesign/'
      path: '/redesign'
      fullPath: '/redesign/'
      preLoaderRoute: typeof RedesignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/new': {
      id: '/workflow/new'
      path: '/workflow/new'
      fullPath: '/workflow/new'
      preLoaderRoute: typeof WorkflowNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/new/': {
      id: '/workflow/new/'
      path: '/'
      fullPath: '/workflow/new/'
      preLoaderRoute: typeof WorkflowNewIndexRouteImport
      parentRoute: typeof WorkflowNewRoute
    }
    '/workflow/$workflowId/edit': {
      id: '/workflow/$workflowId/edit'
      path: '/workflow/$workflowId/edit'
      fullPath: '/workflow/$workflowId/edit'
      preLoaderRoute: typeof WorkflowWorkflowIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$workflowId/edit/': {
      id: '/workflow/$workflowId/edit/'
      path: '/'
      fullPath: '/workflow/$workflowId/edit/'
      preLoaderRoute: typeof WorkflowWorkflowIdEditIndexRouteImport
      parentRoute: typeof WorkflowWorkflowIdEditRoute
    }
    '/workflow/new/step/$step': {
      id: '/workflow/new/step/$step'
      path: '/step/$step'
      fullPath: '/workflow/new/step/$step'
      preLoaderRoute: typeof WorkflowNewStepStepRouteImport
      parentRoute: typeof WorkflowNewRoute
    }
    '/workflow/$workflowId/edit/step/$step': {
      id: '/workflow/$workflowId/edit/step/$step'
      path: '/step/$step'
      fullPath: '/workflow/$workflowId/edit/step/$step'
      preLoaderRoute: typeof WorkflowWorkflowIdEditStepStepRouteImport
      parentRoute: typeof WorkflowWorkflowIdEditRoute
    }
  }
}

interface WorkflowNewRouteChildren {
  WorkflowNewIndexRoute: typeof WorkflowNewIndexRoute
  WorkflowNewStepStepRoute: typeof WorkflowNewStepStepRoute
}

const WorkflowNewRouteChildren: WorkflowNewRouteChildren = {
  WorkflowNewIndexRoute: WorkflowNewIndexRoute,
  WorkflowNewStepStepRoute: WorkflowNewStepStepRoute,
}

const WorkflowNewRouteWithChildren = WorkflowNewRoute._addFileChildren(
  WorkflowNewRouteChildren,
)

interface WorkflowWorkflowIdEditRouteChildren {
  WorkflowWorkflowIdEditIndexRoute: typeof WorkflowWorkflowIdEditIndexRoute
  WorkflowWorkflowIdEditStepStepRoute: typeof WorkflowWorkflowIdEditStepStepRoute
}

const WorkflowWorkflowIdEditRouteChildren: WorkflowWorkflowIdEditRouteChildren =
  {
    WorkflowWorkflowIdEditIndexRoute: WorkflowWorkflowIdEditIndexRoute,
    WorkflowWorkflowIdEditStepStepRoute: WorkflowWorkflowIdEditStepStepRoute,
  }

const WorkflowWorkflowIdEditRouteWithChildren =
  WorkflowWorkflowIdEditRoute._addFileChildren(
    WorkflowWorkflowIdEditRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  WorkflowNewRoute: WorkflowNewRouteWithChildren,
  RedesignIndexRoute: RedesignIndexRoute,
  WorkflowWorkflowIdEditRoute: WorkflowWorkflowIdEditRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
